#!/usr/bin/python
import sys
postings = open("postings", 'r')
wlist = postings.readlines()
postings.close()
dictionary = open("dictionary", "r")
worddict = {}
count = 0
for line in dictionary:
	if count == 0:
		term = line.strip()
		count = count  + 1
	elif count == 1:
		num_file = int(line.strip())
		count = count + 1
	elif count == 2:
		start_pos = int(line.strip()) - 1
		templist = []
		for coords in range(start_pos, start_pos + num_file):
			templist.append(wlist[coords].strip())
		worddict[term] = templist
		count = 0
query_dict = {}
for i in range(1, len(sys.argv),2):
	#print i
	mult = float(sys.argv[1])
	try:
		temp = worddict[sys.argv[i+1].lower()]
	except:
		pass
	#print temp
	#print "----------------------"
	if temp:
		for line in temp:
			line = line.strip()
			line = line.split()
			try:
				query_dict[line[0]] += mult * float(line[1])
			except:
				query_dict[line[0]] = mult * float(line[1])
	else:
		print "Sorry no files could be ranked for the keywords you entered"	
for i in sorted(query_dict.items(), key = lambda x : x[1], reverse = True):
	print i[0] + '.html' + ' ' + str(i[1]) + "\n"
