#!/usr/bin/python
import sys
#Open the psotings file
postings = open("postings", 'r')
#Read the postings file 
wlist = postings.readlines()
postings.close()
#Open the dictionary file
dictionary = open("dictionary", "r")
dictionary.close()
worddict = {}
count = 0
#Read through every entry that has been retrieved from the dictionary
for line in dictionary:
	#Signifies I have read the word
	if count == 0:
		term = line.strip()
		count = count  + 1
	#Signifies that I have read the number of files which contain the given index term
	elif count == 1:
		num_file = int(line.strip())
		count = count + 1
	#Signifies the starting position of the file listing in the postings file
	elif count == 2:
		start_pos = int(line.strip()) - 1
		templist = []
		for coords in range(start_pos, start_pos + num_file):
			templist.append(wlist[coords].strip())
		worddict[term] = templist
		count = 0
query_dict = {}
#Defining  an empty query dictionary
temp = []
#Iterating through every element that has been passed in the arguement array
for i in sys.argv[1:]:
	#print i
	try:
		temp = worddict[i.lower()]
	except:
		pass
	#print temp
	#print "----------------------"
	if temp:
		for line in temp:
			line = line.strip()
			line = line.split()
			try:
				query_dict[line[0]] += float(line[1])
			except:
				query_dict[line[0]] = float(line[1])
	else:
		print "No ranking could be derived. Im Sorry, but I have m limitations. I am just not that into the entered keyword"
for i in sorted(query_dict.items(), key = lambda x : x[1], reverse = True):
	print i[0] + '.html' + ' ' + str(i[1]) + "\n"
